language: node_js
node_js:
  - '10'
dist: trusty
sudo: required

cache: yarn

branches:
  only:
    - master

before_install:
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install apt-transport-https azure-cli
  - az login -u $AZ_LOGIN_NAME -p $AZ_PASSWORD --service-principal --tenant $AZ_TENANT > /dev/null 2>&1

script:
  - yarn
  - yarn build
  - yarn export

after_success:
  - az storage blob upload-batch -d \$web -s ./out
